### PR TITLE
Combine hdijupyterutils, sparkmagic and autovizwidget into one feedstock

### PR DESCRIPTION
**Pull request by ericdill**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

First pass at implementing what's discussed in #8 . cc @dbast @danielfrg @itamarst

### CODE REVIEW

**Comment by dbast** [comment]
How are the files `pre-unlink.sh` and `post-link.sh` handled, which are only required by the `sparkmagic` subpackage?

**Comment by ericdill** [comment]
@dbast that's a good question. Let me investigate

**Comment by ericdill** [comment]
@dbast, Because there are post-link scripts sparkmagic can't be a noarch: python recipe. My fault for not catching this earlier.

**Comment by dbast** [comment]
@ericdill Maybe not necessarily as I see when inspecting: `https://anaconda.org/conda-forge/jupyterlab_code_formatter/0.3.0/download/noarch/jupyterlab_code_formatter-0.3.0-py_0.tar.bz2` 

```
tree
.
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── LICENSE.txt
│   ├── link.json
│   ├── paths.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   ├── meta.yaml.template
│   │   ├── post-link.bat
│   │   ├── post-link.sh
│   │   ├── pre-unlink.bat
│   │   └── pre-unlink.sh
│   └── test
│       └── run_test.py
├── python-scripts
├── share
│   └── jupyter
│       └── lab
│           └── extensions
│               └── ryantam626-jupyterlab_code_formatter-0.3.0-9035e800e45a762d033c523c5e8ed1340caa807d.tgz
└── site-packages
    ├── jupyterlab_code_formatter
    │   ├── formatters.py
    │   ├── handlers.py
    │   └── __init__.py
    └── jupyterlab_code_formatter-0.3.0.dist-info
        ├── INSTALLER
        ├── LICENSE
        ├── METADATA
        ├── RECORD
        ├── top_level.txt
        └── WHEEL
```

It is noarch but including post-lin/pre-unlink .sh and .bat files that can be executed depending on where the package is installed.

**Pull request closed without merging**
